### ISSUE TITLE
Add a link to the supported rules to clarify

### ISSUE THREAD

**Issue by rajbos** [philips-labs/continuous-compliance-action#23]
This looks super helpful (and something that was on my backlog to search for!). 

I couldn’t find an explanation of the supported rules and how they work? That a file exists is straightforward, but what more is possible? I have some ideas for that 😬. 

Can there be a link with that info in the readme?

**Comment by Brend-Smits** [comment]
Hey @rajbos,

Apologies for the delayed reply. I missed this issue in the sea of notifications...
This action uses Repolinter under the hood, they have their documentation available here: https://github.com/todogroup/repolinter/blob/main/docs/rules.md

Might be a good idea to clarify our documentation to include some information about this. Hope it helps and please don't hesitate to reach out if you need additional help.
